### PR TITLE
add trip budgeter

### PR DESCRIPTION
**Pull request by shubhagarwal1**
fix: #78 
Screenshot 2024-10-17 at 1 59 55 AM

### CODE REVIEW

**Comment by Mustafiz04** [comment]
Same do better styling. Functionality look good.

**Comment by Mustafiz04** [comment]
Also add budget for International destinations.

**Comment by shubhagarwal1** [comment]
> Same do better styling. Functionality look good.

okay. i will try to imporve the styling of the page

**Comment by shubhagarwal1** [comment]
> Also add budget for International destinations.

we have caluclator for inr ,euros, and dollars
so what else should i add please tell

**Comment by shubhagarwal1** [comment]
> Same do better styling. Functionality look good.

can you merge this, i will improve the styling in next PR ipossible, you can make it level 2 for now

**Review by Mustafiz04 — APPROVED** [review]

**Pull request merged**
