### PR TITLE
Added hotel booking system

### PR DESCRIPTION
**Pull request by KapuluruBhuvaneswariVspdbct**
1.created booking button in navbar
2.Added form to the booking page
3.Form is added
4.it consists of states on selecting state relevant hotels  will be displayed
5.after submiting a card for confirmation shown
6.yourbookings button added to navbar
7.yourbookings consists of all the booked thing
8.cancel option will also work if it is confirm message to cancel

https://github.com/user-attachments/assets/87cf7e47-2cde-4b85-ba98-dfe551605fef

Screenshot 2024-10-17 043905

### CODE REVIEW

**Comment by KapuluruBhuvaneswariVspdbct** [comment]
sir, for dynamic map locations api is required which is to buy for $200 
so i put my efforts and gathered all the information and done multiple tasks .
by considering my efforts please give score atleaset above 65 marks 

https://github.com/user-attachments/assets/0d6ce588-bf07-49ab-b4f2-1dc412b05187

**Comment by Mustafiz04** [comment]
Functionality look good but can you please ensure to have better UI ? Add some styling

**Comment by KapuluruBhuvaneswariVspdbct** [comment]
Ok I will can you tell me the marks that  u can add

**Comment by Mustafiz04** [comment]
> Ok I will can you tell me the marks that u can add
> 
Already added level 3

**Comment by KapuluruBhuvaneswariVspdbct** [comment]
i Have changed the ui sir

**Comment by Mustafiz04** [comment]
Please don't use these background colours. Make is minimal UI.

The feature looks good but the UI and styling. Styling should be consistent.

**Comment by KapuluruBhuvaneswariVspdbct** [comment]
what should i do now

**Comment by KapuluruBhuvaneswariVspdbct** [comment]
suggest some colors sir

**Comment by KapuluruBhuvaneswariVspdbct** [comment]
changed styling sir 
Made solved 2 issues worked on two level3 issues kindly merge this pull request allot marks for both the issues solving
#87 
#88 
https://github.com/user-attachments/assets/094c8fd4-1f70-48c0-b169-aa227feb7b0b

**Comment by KapuluruBhuvaneswariVspdbct** [comment]
@Mustafiz04 please merge this pull request

**Review by Mustafiz04 — APPROVED** [review]

**Pull request merged**
