### PR TITLE
Updated navbar to fixed at top, updated footer social icons

### PR DESCRIPTION
**Pull request by Nitinkumar-29**
This pull request consist some basic change in ui with updated fixed navbar position to keep it at top without any side effect.

Also updated social icons with react icons, including adding new twitter X icon in place of old with some animated effects.

### CODE REVIEW

**Review by Nitinkumar-plutos — COMMENTED** [review]
Ok, this code seems to be fine as it doesn't effect any other part if UI , functionality.

**Review by Nitinkumar-plutos — APPROVED** [review]

**Review by Nitinkumar-plutos — APPROVED** [review]
Yes, It is fine

**Comment by Mustafiz04** [comment]
Can you please add a screenshot for these changes?

**Comment by Nitinkumar-29** [comment]
Yes, for sure 
Here is screenshot for the proof of my work, changes made in code
Screenshot 2024-10-14 212155

As you can see scrollbar is at bottom, navbar is fixed at top and footer social icons are updated including twitter old icon.

**Comment by Mustafiz04** [comment]
That is cool but I see the letter `a` here.

Screenshot 2024-10-15 at 10 16 49 AM

**Review by Mustafiz04 — APPROVED** [review]

**Comment by AKSHITHA-CHILUKA** [comment]
add level labels @Mustafiz04

**Pull request merged**
