### PR TITLE
#Add Github Actions Bot & Code of Conduct Md file

### LINKED ISSUE #14: (Documentation) : Add code of conduct & Github Greetings Bot
Hey 🥳 Looks like an amazing project idea! I see this repo lacks a small enhancement Github Greetings bot that sends auto messages to greet new users when they raise a PR or an issue. Let me know if you would like this level1 set up! Please assign to me if interested! (GSSoC24-Ext Contribution), I will also add code of conduct as per the standard norms followed by GSSoC24.

### PR DESCRIPTION
**Pull request by ghost**
closes #14 

This PR has been raised to address the following issues.

1. A github actions bot that displays a message in the form of comments to new users who raise a fresh issue or PR in the repository.
2. A github actor bot that auto assigns the issue to whoever raised or created the issue. Unassign is still manual.
3. Code of conduct markdown file based on the standards followed by organisations worldwide. The email ID of the author has been added for reporting purposes.

Please review and action accordingly. 

Please add level1 and gssoc-ext labels to this PR.

Thank you!

### CODE REVIEW

**Comment by Mustafiz04** [comment]
Please squash your commits into 1 commit.

**Comment by KiranBaliga** [comment]
@Mustafiz04 Pardon, how do I do that? these three files do different action of their own.

**Comment by Mustafiz04** [comment]
You still have 5 commits, you should have 1 commit per PR.

Follow these steps to squash commits.
```
git reset --soft $(git merge-base main HEAD)
git add .
git commit -m 'commit message'
git push origin <branch-name> --force-with-l
```

**Comment by Mustafiz04** [comment]
@KiranBaliga please update

**Comment by KiranBaliga** [comment]
@Mustafiz04 Apologies, my PC has died on me, give me two days and I will get all the commits squashed.

**Review by Mustafiz04 — APPROVED** [review]

**Pull request merged**
