### PR TITLE
Add review page

### PR DESCRIPTION
**Pull request by shubhagarwal1**
fix: #79 
Screenshot 2024-10-17 at 2 21 07 AM

### CODE REVIEW

**Comment by Mustafiz04** [comment]
Can you please ensure to have better UI to look minimal and consistent in all the pages ?

**Comment by shubhagarwal1** [comment]
> Can you please ensure to have better UI to look minimal and consistent in all the pages ?
yes i tried implementing the same and tried to keep everything very minimilistic 
can you please let me know what changes are you looking for.

**Comment by Mustafiz04** [comment]
This means styling should be consistent. While background, UI alignment and so

**Comment by Mustafiz04** [comment]
Please rebase and merge the conflict.

**Comment by shubhagarwal1** [comment]
solved th conflicts

**Comment by shubhagarwal1** [comment]
> Please rebase and merge the conflict.

done

**Review by Mustafiz04 — APPROVED** [review]

**Comment by Mustafiz04** [comment]
Again conflict.

**Comment by Mustafiz04** [comment]
@shubhagarwal1

**Comment by shubhagarwal1** [comment]
> @shubhagarwal1

Hey @Mustafiz04 i am so Sorry for the delay

**Comment by shubhagarwal1** [comment]
Hey @Mustafiz04 please merge this as this has changes to file that may be pushed by others also, so conflicts will rise again , order to avoid thsi please merge this

**Review by Mustafiz04 — APPROVED** [review]

**Pull request merged**
