### PR TITLE
Updated Navbar and Readme File

### LINKED ISSUE #30: Update Readme file
Good evening @Mustafiz04  sir, 
I saw that the readme file is not updated . 
image
I would like to create a new readme file and update all the information so that people will get to know more about the project.
So if you could please assign me this issue with the relevant labels and levels , it would be really grateful.
Thank you

### LINKED ISSUE #38: Navbar Enhancement | Sticky Navbar
The Navbar should be sticky for better UX.

### PR DESCRIPTION
**Pull request by Shreeya2002**
closes #38 
closes #30 
---

## Pull Request Title:  
**Fix: Sticky Navbar for Improved UX and Updated README**

---

### Description:

This pull request addresses the following issues:

1. **Improved UX with Sticky Navbar:**
   - Updated the `navbar` to have a fixed (sticky) position, ensuring better navigation and consistent visibility across all pages. This change enhances user experience by keeping the navigation bar accessible at all times.

2. **Updated README:**
   - Revised the README file to include clear and concise installation steps, including:
     - Cloning the repository
     - Installing dependencies
     - Running the development server
   - Added contribution guidelines for forking, branching, and submitting pull requests, making it easier for contributors to get started.

### CODE REVIEW

**Comment by Mustafiz04** [comment]
Can you add screenshot for reference ???

**Comment by Shariq2003** [comment]
> ## closes #38
> closes #30
> ## Pull Request Title:
> **Fix: Sticky Navbar for Improved UX and Updated README**
> 
> ### Description:
> This pull request addresses the following issues:
> 
> 1. **Improved UX with Sticky Navbar:**
>    
>    * Updated the `navbar` to have a fixed (sticky) position, ensuring better navigation and consistent visibility across all pages. This change enhances user experience by keeping the navigation bar accessible at all times.
> 2. **Updated README:**
>    
>    * Revised the README file to include clear and concise installation steps, including:
>      
>      * Cloning the repository
>      * Installing dependencies
>      * Running the development server
>    * Added contribution guidelines for forking, branching, and submitting pull requests, making it easier for contributors to get started.

@Shreeya2002 how u can work on the issue that I created, even though u have not assigned for that.

**Comment by Shariq2003** [comment]
> Can you add screenshot for reference ???

@Mustafiz04 this PR is invalid as this issue is created by me, and also @Shreeya2002 is not assigned for this issue #38

**Comment by Mustafiz04** [comment]
I see. Closing this one

**Pull request closed without merging**
