### PR TITLE
Multi-Language Support Using Language Translator

### PR DESCRIPTION
**Pull request by TBorundia**
Issue: #148

I have added Multi-Language Support Using Language Translator API that will helps to convert the website text to the multiple country languages.

https://github.com/user-attachments/assets/d1218db6-e1a3-4a3f-bfd7-553d85e2b2aa

### CODE REVIEW

**Comment by TBorundia** [comment]
@Mustafiz04 , by default website will be in English only.
Where should I place the translator??

**Comment by TBorundia** [comment]
@Mustafiz04 , Ok I will work on it.

**Comment by TBorundia** [comment]
@Mustafiz04 , I have aligned the translator with icons. But the by default English selection is not working.
But once the language has been selected then 'Select language' will disappear and only language choice will be their.

image

**Review by Mustafiz04 — APPROVED** [review]

**Comment by Mustafiz04** [comment]
Please rebase and resolve the merge conflict.

**Comment by TBorundia** [comment]
@Mustafiz04 , Solved the conflicts.
Please review it now.
Thank You!!

**Comment by TBorundia** [comment]
@Mustafiz04  , I have resolved the conflicts .
Please review it as soon as possible. Thank You!!

**Comment by TBorundia** [comment]
@Mustafiz04 ??

**Comment by Mustafiz04** [comment]
Again conflict

**Comment by TBorundia** [comment]
@Mustafiz04 , Check it now!!

**Pull request merged**
