### PR TITLE
Design About-Us page also add FAQ Section in home page.

### PR DESCRIPTION
**Pull request by mdfaizaanalam**
I have fix the Issue #49 

### Before About Us page:

Screenshot 2024-10-12 192730

### After modification About-Us page:

https://github.com/user-attachments/assets/8e973bb5-93bf-44ee-bb8a-5750e74998a4

As you can see above screenshot of about us page it is very simple. So i re-design about us page with modern ui features, add typing-text effect, material-ui, motiom imag, also add testimonial card with avatar image and star rating contains,

---

### Before home page there is no FAQ Section: 

Screenshot 2024-10-14 152519

### After Home Page with FAQ Section:

https://github.com/user-attachments/assets/fa2d6ddf-12ed-439d-a936-222ec5eeda74

Also in above image you can see in home page there is not FAQ section so i add new responsive FAQ section in home page.

### CODE REVIEW

**Comment by mdfaizaanalam** [comment]
@Mustafiz04 Please check, i have created complete **About-Us** Page and also Add the **FAQ** Section in **Home-Page**.

Also i request you to please add level 3 in it.

**Review by Mustafiz04 — APPROVED** [review]
Look good to me. Good work.

**Comment by mdfaizaanalam** [comment]
@Mustafiz04 I request you to please add label in it.
hacktoberfest-accepted
gssoc-ext
Level 3

**Comment by mdfaizaanalam** [comment]
@Mustafiz04  Please add labels in it.

hacktoberfest-accepted
gssoc-ext
Level 3

**Comment by mdfaizaanalam** [comment]
@Mustafiz04 @aqueefcs  My contribution is not showing in leaderboard due to unavailability of labels in it.
I request you to please add labels in it.

hacktoberfest-accepted
gssoc-ext
Level 3

**Pull request merged**
