### PR TITLE
Fix heading color issues

### PR DESCRIPTION
**Pull request by MuhammadAshraf23**
**Summary**
This pull request addresses visibility issues in the headings "You Travel the World" and "Explore the World" where the text was rendered invisible due to matching the background color. The color of the text has been updated to ensure proper visibility against the background.

**Changes Made**
Updated the Homepage.jsx file to improve text visibility for both headings.
Applied contrasting colors to the text to enhance readability, ensuring that all words are clearly visible.
Maintained the existing styling where applicable for design consistency.
**Issue Reference**
This PR fixes issue #42, where multiple headings had text that was not visible against the background.

**Testing**
The changes have been tested locally to ensure that both headings are now fully visible against the background.
**Screenshots:**
**Before:**
image
image

**After:**
image
image

**Additional Notes**
Please let me know if any further adjustments are needed.
I welcome any suggestions for improving the styles or any additional feedback.

### CODE REVIEW

**Comment by MuhammadAshraf23** [comment]
@Mustafiz04 please review

**Comment by Mustafiz04** [comment]
Please rebase with the main branch

Screenshot 2024-10-14 at 9 20 11 PM

**Comment by MuhammadAshraf23** [comment]
> Please rebase with the main branch
> 
> Screenshot 2024-10-14 at 9 20 11 PM
> Also check this one login - /signin

Yeah i changed This Also

**Comment by MuhammadAshraf23** [comment]
@Mustafiz04 @aqueefcs
 I've resolved the merge conflict. Please review the changes and let me know if there's anything else needed.

**Review by Mustafiz04 — APPROVED** [review]

**Pull request merged**
