### PR TITLE
enhanced booking page

### PR DESCRIPTION
**Pull request by AswaniBolisetti**
@Mustafiz04 
I have enhanced the booking page from this
booking2 mp4
to this

https://github.com/user-attachments/assets/ff014768-909d-4ab9-a2fe-74d8a560608c

Kindly check it out

### CODE REVIEW

**Comment by AswaniBolisetti** [comment]
@Mustafiz04 Kindly approve it and please add the labels too

**Comment by AswaniBolisetti** [comment]
@Mustafiz04 Kindly approve it and merge it 
Please

**Comment by AswaniBolisetti** [comment]
@Mustafiz04 please merge this

**Comment by AswaniBolisetti** [comment]
@Mustafiz04 
Please merge this

**Review by Mustafiz04 — APPROVED** [review]

**Comment by AswaniBolisetti** [comment]
@Mustafiz04 
If possible please consider it as level3

**Pull request merged**
