### PR TITLE
changes have been added for Signup page not visible #119

### PR DESCRIPTION
**Pull request by Sivasaiklu**
@Mustafiz04
 I have changed the color for thr register button, now it is visible

image

### CODE REVIEW

**Comment by Sivasaiklu** [comment]
I request @Mustafiz04 to check my pull request and approve

**Comment by Sivasaiklu** [comment]
@Mustafiz04  please approve my previous review

**Comment by Sivasaiklu** [comment]
image

image

sir I have added the chatbot also @Mustafiz04  check once and give me level2 badge if possible

@Mustafiz04 sir see the pull request and merge it sir

**Comment by Mustafiz04** [comment]
Do chatbot in separate PR please

**Comment by Sivasaiklu** [comment]
> Do chatbot in separate PR please

sir can you say how to separte PR please

**Pull request closed without merging**
